### PR TITLE
feat/aboutus component

### PR DESCRIPTION
**Pull request by IgrPhillipe**
**Things I've done:**

- Create a responsive about us section
- I got the about us data from the database via backend route and used on the front end.

**How to test it:**

- First download the node modules on the client and the server. If you have already done that, then:
- Change the values on .env.
- Go to client on the terminal (cd client) and put npm run start.
- On the browser write http://localhost:3000.
- See if the about us section works both in mobile and desktop view.
- Look at the code to see if it has everything that it should have.

### CODE REVIEW

**Comment by JulioBem** [comment]
The footer section is commented out in _"index.jsx"_ and the _About Us_ section is under the footer instead of showing up above it. Aside those things, everything is perfect as far as I can see. Good job!!

**Review by JulioBem — CHANGES_REQUESTED** [review]
The footer section is commented out in _"index.jsx"_ and the _About Us_ section is under the footer instead of showing up above it. Aside those things, everything is perfect as far as I can see. Good job!!

**Review by Sofiamdl — CHANGES_REQUESTED** [review]
The gallery isn't being exported in index.jsx (besides that everything is really good :) )

**Comment by IgrPhillipe** [comment]
The gallery isn't ready yet, i've forgot to remove the import

**Review by JulioBem — APPROVED** [review]

**Pull request merged**
