### PR TITLE
Feat/services

### PR DESCRIPTION
**Pull request by Sofiamdl**
Things I've done:

-  Create the Our Services section responsively
-  Get the information for each Our Services item registered in the database, via the back-end route
-  Use the information that was picked up from the back-end on the Our Services carousel

How to test it:

-  First download the node modules on the client and the server. If you have already done that, then:
-  Change the values on .env.
-  Go to client on the terminal (cd client) and put npm run start.
-   Go to server on the terminal (cd server) and put node .\index.js
-  On the browser write http://localhost:3000/.
-  See if the "ourServices" works in mobile and desktop view.
-  Look at the code to see if it has everything that it should have.

### CODE REVIEW

**Review by IgrPhillipe — APPROVED** [review]
The entire session is working perfectly, I didn't find any errors. Good job! :))

**Review by JulioBem — CHANGES_REQUESTED** [review]
When the text is larger it overflows on top of the image instead of creating some sort of scrolling down or maybe a dynamic div would solve the issue too.

**Comment by JulioBem** [comment]
The page on web view is also with horizontal scroll.

**Review by JulioBem — APPROVED** [review]
The problems were solved and it looks pretty good. Well done.

**Pull request merged**
